
ALTER TABLE users
    RENAME COLUMN "refreshtoken" TO "refreshToken";

ALTER TABLE users
    ADD COLUMN "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
